import os
from pathlib import Path
from src.utils.types.Language import Language

def return_full_path(path_complement):
    return os.path.join(Path(__file__).parent.resolve(), '..', '..', path_complement)

def make_dict_types(language: Language):

    if language == Language.PYTHON:
        return {
            'ENDMARKER': 0,
            'NAME': 0,
            'NUMBER': 0,
            'STRING': 0,
            'NEWLINE': 0,
            'INDENT': 0,
            'DEDENT': 0,
            'LPAR': 0,
            'RPAR': 0,
            'LSQB': 0,
            'RSQB': 0,
            'COLON': 0,
            'COMMA': 0,
            'SEMI': 0,
            'PLUS': 0,
            'MINUS': 0,
            'STAR': 0,
            'SLASH': 0,
            'VBAR': 0,
            'AMPER': 0,
            'LESS': 0,
            'GREATER': 0,
            'EQUAL': 0,
            'DOT': 0,
            'PERCENT': 0,
            'LBRACE': 0,
            'RBRACE': 0,
            'EQEQUAL': 0,
            'NOTEQUAL': 0,
            'LESSEQUAL': 0,
            'GREATEREQUAL': 0,
            'TILDE': 0,
            'CIRCUMFLEX': 0,
            'LEFTSHIFT': 0,
            'RIGHTSHIFT': 0,
            'DOUBLESTAR': 0,
            'PLUSEQUAL': 0,
            'MINEQUAL': 0,
            'STAREQUAL': 0,
            'SLASHEQUAL': 0,
            'PERCENTEQUAL': 0,
            'AMPEREQUAL': 0,
            'VBAREQUAL': 0,
            'CIRCUMFLEXEQUAL': 0,
            'LEFTSHIFTEQUAL': 0,
            'RIGHTSHIFTEQUAL': 0,
            'DOUBLESTAREQUAL': 0,
            'DOUBLESLASH': 0,
            'DOUBLESLASHEQUAL': 0,
            'AT': 0,
            'ATEQUAL': 0,
            'RARROW': 0,
            'ELLIPSIS': 0,
            'COLONEQUAL': 0,
            'OP': 0,
            'AWAIT': 0,
            'ASYNC': 0,
            'TYPE_IGNORE': 0,
            'TYPE_COMMENT': 0,
            'SOFT_KEYWORD': 0,
            'ERRORTOKEN': 0,
            'N_TOKENS': 0,
            'NT_OFFSET': 0,
            'COMMENT': 0,
            'NL': 0,
            'ENCODING': 0,
            'TYPE_COMMENT': 0
        }
    else:
        return {
            'LexerError': 0,
            'Position': 0,
            'JavaToken': 0,
            'EndOfInput': 0,
            'Keyword': 0,
            'Modifier': 0,
            'BasicType': 0,
            'Literal': 0,
            'Integer': 0,
            'DecimalInteger': 0,
            'OctalInteger': 0,
            'BinaryInteger': 0,
            'HexInteger': 0,
            'FloatingPoint': 0,
            'DecimalFloatingPoint': 0,
            'HexFloatingPoint': 0,
            'Boolean': 0,
            'Character': 0,
            'String': 0,
            'Null': 0,
            'Separator': 0,
            'Operator': 0,
            'Annotation': 0,
            'Identifier': 0
        }